"""Classification rules for sender type taxonomy."""

# Sender type classification rules
SENDER_TYPES = {
    "newsletter": {
        "description": "Newsletters and subscriptions",
        "signals": ["unsubscribe", "view in browser", "email preferences", "manage preferences"],
        "from_patterns": ["newsletter@", "news@", "digest@", "weekly@", "daily@"],
        "subject_patterns": ["newsletter", "weekly digest", "daily digest"],
        "priority": 10,
    },
    "transactional": {
        "description": "Order confirmations, receipts, shipping updates",
        "signals": [],
        "from_patterns": [
            "orders@",
            "noreply@",
            "no-reply@",
            "receipts@",
            "invoice@",
            "billing@",
            "shipping@",
            "delivery@",
        ],
        "subject_patterns": [
            "order",
            "receipt",
            "confirmation",
            "shipped",
            "delivered",
            "invoice",
            "payment",
            "tracking",
        ],
        "priority": 20,
    },
    "marketing": {
        "description": "Promotional emails and offers",
        "signals": ["unsubscribe", "% off", "sale", "deal", "limited time", "special offer"],
        "from_patterns": ["promo@", "marketing@", "deals@", "offers@", "sales@"],
        "subject_patterns": [
            "% off",
            "sale",
            "deal",
            "discount",
            "limited time",
            "special offer",
            "exclusive",
            "save",
            "free shipping",
        ],
        "priority": 15,
    },
    "automated": {
        "description": "Security alerts, password resets, verification emails",
        "signals": [],
        "from_patterns": [
            "security@",
            "alerts@",
            "notifications@",
            "support@",
            "account@",
            "verify@",
            "auth@",
        ],
        "subject_patterns": [
            "password reset",
            "login alert",
            "security",
            "verification",
            "verify",
            "confirm your",
            "action required",
            "unusual activity",
            "sign in",
        ],
        "priority": 25,
    },
    "social": {
        "description": "Social media notifications",
        "signals": [],
        "from_patterns": [
            "linkedin",
            "twitter",
            "facebook",
            "instagram",
            "tiktok",
            "youtube",
            "reddit",
            "pinterest",
            "snapchat",
            "whatsapp",
            "telegram",
            "discord",
            "slack",
        ],
        "subject_patterns": [
            "new follower",
            "new connection",
            "liked your",
            "commented on",
            "mentioned you",
            "new message",
            "invitation",
        ],
        "priority": 30,
    },
    "personal": {
        "description": "Personal emails from individuals",
        "signals": [],
        "from_patterns": [
            "@gmail.com",
            "@outlook.com",
            "@yahoo.com",
            "@hotmail.com",
            "@icloud.com",
            "@aol.com",
            "@protonmail.com",
            "@live.com",
        ],
        "subject_patterns": [],
        "low_volume": True,
        "priority": 100,  # Low priority - fallback for personal domains
    },
    "professional": {
        "description": "Work-related emails from colleagues or partners",
        "signals": [],
        "from_patterns": [],  # Dynamic - inferred from user's domain
        "subject_patterns": [
            "meeting",
            "call",
            "follow up",
            "proposal",
            "contract",
            "project",
            "deadline",
            "review",
            "feedback",
        ],
        "dynamic": True,
        "priority": 50,
    },
    "financial": {
        "description": "Bank statements, investment updates, financial alerts",
        "signals": [],
        "from_patterns": [
            "bank",
            "chase",
            "wells fargo",
            "citi",
            "capital one",
            "amex",
            "visa",
            "mastercard",
            "paypal",
            "venmo",
            "zelle",
            "stripe",
            "square",
        ],
        "subject_patterns": [
            "statement",
            "balance",
            "transaction",
            "payment",
            "transfer",
            "deposit",
            "withdrawal",
            "account alert",
        ],
        "priority": 35,
    },
    "travel": {
        "description": "Flight confirmations, hotel bookings, travel updates",
        "signals": [],
        "from_patterns": [
            "airline",
            "united",
            "delta",
            "american",
            "southwest",
            "jetblue",
            "expedia",
            "booking.com",
            "airbnb",
            "hotels",
            "marriott",
            "hilton",
            "uber",
            "lyft",
        ],
        "subject_patterns": [
            "flight",
            "booking",
            "reservation",
            "itinerary",
            "check-in",
            "boarding",
            "trip",
            "hotel",
        ],
        "priority": 40,
    },
    "unknown": {
        "description": "Unclassified emails",
        "signals": [],
        "from_patterns": [],
        "subject_patterns": [],
        "priority": 999,  # Fallback
    },
}

# Actions suggested for each category
CATEGORY_ACTIONS = {
    "newsletter": {
        "keep": "Read regularly to stay informed",
        "unsubscribe": "Consider unsubscribing if not read in 30+ days",
        "archive": "Archive after reading",
    },
    "transactional": {
        "keep": "Keep for 30-90 days for reference",
        "archive": "Archive after order complete",
        "delete": "Safe to delete after 90 days for routine orders",
    },
    "marketing": {
        "delete": "Often safe to delete after initial scan",
        "unsubscribe": "Unsubscribe from unwanted promotions",
        "archive": "Archive deals you might use later",
    },
    "automated": {
        "keep": "Keep security alerts for 30 days",
        "delete": "Safe to delete password reset emails after use",
        "archive": "Archive important account notifications",
    },
    "social": {
        "delete": "Generally safe to delete - info available on platform",
        "archive": "Archive important connection requests",
    },
    "personal": {
        "keep": "Keep indefinitely or archive",
        "archive": "Archive older conversations",
    },
    "professional": {
        "keep": "Keep work-related emails per company policy",
        "archive": "Archive completed projects",
    },
    "financial": {
        "keep": "Keep for tax/audit purposes (7+ years for tax docs)",
        "archive": "Archive monthly statements",
    },
    "travel": {
        "keep": "Keep until trip complete + 30 days",
        "delete": "Safe to delete after travel complete",
    },
    "unknown": {
        "review": "Manually review and categorize",
    },
}
